version: '{build}'
branches:
  only:
  - noautobuilds
skip_tags: true
os: Visual Studio 2015
configuration: Release
init:
- ps: Update-AppveyorBuild -Version "1.$(Get-Date -format yyyy.M).$env:appveyor_build_number"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: normal
after_build:
- cmd: >-
    nuget pack Cinteros.XrmToolBox.Plugins.nuspec -Version %APPVEYOR_BUILD_VERSION%
    7z a Cinteros.XrmToolBox.Plugins_%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Output\%CONFIGURATION%\Cinteros.Xrm.*.dll
    appveyor PushArtifact Cinteros.XrmToolBox.Plugins_%APPVEYOR_BUILD_VERSION%.zip
artifacts:
- path: '**\Cinteros.Xrm.Plugins.*.nupkg'
deploy:
- provider: Environment
  name: GitHubCintXTB
- provider: FTP
  host: rappen.net
  protocol: ftp
  username: Jonas
  password:
    secure: tlAywufGDNedgIwqqBUmsA==
  folder: rappen/Cinteros
- provider: NuGet
  api_key:
    secure: e85PnghtumEbD21fvXX7r3CO36xJeFS3kwrPx25rlpa57M5ztBvFjlKAbP85icZA
  skip_symbols: true
  artifact: /.*\.nupkg/